require 'hoe'
require './lib/mooncats/graphql/version.rb'

Hoe.spec 'mooncats-graphql' do

  self.version = MooncatsClient::VERSION

  self.summary = "mooncats-graphql - (lite) mooncats (http json) graphql api / client"
  self.description = summary

  self.urls    = { home: 'https://github.com/cryptocopycats/mooncats' }

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.3'
  }

end
